-- CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
insert into productos (name, price) values ('Wine - White, Gewurtzraminer', 257.17);
insert into productos (name, price) values ('The Pop Shoppe - Grape', 86.59);
insert into productos (name, price) values ('Shrimp, Dried, Small / Lb', 452.06);
insert into productos (name, price) values ('Kaffir Lime Leaves', 235.79);
insert into productos (name, price) values ('Oil - Sesame', 312.22);
insert into productos (name, price) values ('Muffin Mix - Blueberry', 231.39);
insert into productos (name, price) values ('Cactus Pads', 586.28);
insert into productos (name, price) values ('Wine - Manischewitz Concord', 870.22);
insert into productos (name, price) values ('Nutmeg - Ground', 947.56);
insert into productos (name, price) values ('Sachet', 581.02);
insert into productos (name, price) values ('Turkey - Whole, Fresh', 427.49);
insert into productos (name, price) values ('Lemonade - Pineapple Passion', 590.28);
insert into productos (name, price) values ('Towel Dispenser', 155.23);
insert into productos (name, price) values ('Pail With Metal Handle 16l White', 97.01);
insert into productos (name, price) values ('Nantucket Pine Orangebanana', 309.2);
insert into productos (name, price) values ('Coffee - Dark Roast', 87.05);
insert into productos (name, price) values ('Tea - Earl Grey', 147.02);
insert into productos (name, price) values ('Tomatoes - Yellow Hot House', 909.16);
insert into productos (name, price) values ('Sole - Fillet', 481.55);
insert into productos (name, price) values ('Beer - Labatt Blue', 494.14);
